from setuptools import setup, find_packages

setup(
    name='capspeech',
    version='0.1.0',
    packages=find_packages(),
    install_requires=[
        'xformers',
        'g2p_en',
        "laion_clap",
        'torchvision',
        'torchaudio',
        'torch',
        'transformers>=4.46.1,<=4.46.1',
        'tensorboard',
        'datasets',
        'torchmetrics',
        'huggingface_hub',
        'cached_path',
        'torchdiffeq',
        'x_transformers',
        'jieba',
        'pypinyin',
        'wandb',
        'ema_pytorch',
        "sentencepiece",
        "descript-audio-codec",
        "descript-audiotools @ git+https://github.com/descriptinc/audiotools",
        "protobuf>=4.0.0",
        "jiwer",
        "accelerate",
        "evaluate",
        "ninja",
        "packaging",
        "wheel"
    ],
    author='Helin Wang',
    description='CapSpeech: Enabling Downstream Applications in Style-Captioned Text-to-Speech',
    url='https://github.com/WangHelin1997/CapSpeech',
    python_requires='>=3.10',
)
